config/routes.rb
Rails.application.routes.draw do

  resources :sends, only: [:create, :new]
  get 'perfil', to: 'perfil#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'geocoder/findaddress'
  get 'pages/index'

  root to: 'pages#index'

  resources :products do
    resources :orders, only: :create
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :orders, only: :index do
    collection do
      get "clean"
    end
  end

  devise_for :users, :controllers => {:registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks"}


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
  scope :cart, -> {where(payed: false)}

  def self.get_total
    pluck("price * quantity").sum()
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity += 1

    if o.save
      redirect_to orders_path, notice: "El producto ha sido agregado al carro."
    else
      redirect_to products_path, alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.cart
    @total = @orders.get_total
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Valor</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td> <%= order.product.name %> </td>
          <td> <%= order.price %></td>
          <td> <%= order.quantity %> </td>
          <td> <%= order.price * order.quantity %></td>
        </tr>
      <% end %>
      <tr class="table-dark">
      <td></td>
      <td></td>
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Limpiar carro',clean_orders_path, class: 'btn btn-outline-danger'  %>
  <%= link_to 'Confirmar Compra', new_send_path, class: 'btn btn-outline-success float-right'%>
  <% else %>
    <p>No tienes productos en tu carro de compra.</p>
  <% end %>

</div>