config/routes.rb
Rails.application.routes.draw do

  resources :sends, only: [:create, :new]
  get 'perfil', to: 'perfil#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'geocoder/findaddress'
  get 'pages/index'

  root to: 'pages#index'

  resources :products do
    resources :orders, only: :create
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :orders, only: :index do
    collection do
      get "clean"
    end
  end

  devise_for :users, :controllers => {:registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks"}


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/send.rb
class Send < ApplicationRecord
  belongs_to :user, :optional => true
  geocoded_by :address
  after_validation :geocode
end

app/controllers/sends_controller.rb
class SendsController < ApplicationController
  before_action :set_send, only: [:show, :edit, :update, :destroy]

  # GET /sends
  # GET /sends.json
  def index
    @sends = Send.all
  end

  # GET /sends/1
  # GET /sends/1.json
  def show
  end

  # GET /sends/new
  def new
    @send = Send.new
  end

  # GET /sends/1/edit
  def edit
  end

  # POST /sends
  # POST /sends.json
  def create
    @send = Send.new(send_params)

    respond_to do |format|
      if @send.save
        format.html { redirect_to pre_pay_billings_path, notice: 'Send was successfully created.' }
        format.json { render :show, status: :created, location: @send }
      else
        format.html { render :new }
        format.json { render json: @send.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sends/1
  # PATCH/PUT /sends/1.json
  def update
    respond_to do |format|
      if @send.update(send_params)
        format.html { redirect_to @send, notice: 'Send was successfully updated.' }
        format.json { render :show, status: :ok, location: @send }
      else
        format.html { render :edit }
        format.json { render json: @send.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sends/1
  # DELETE /sends/1.json
  def destroy
    @send.destroy
    respond_to do |format|
      format.html { redirect_to sends_url, notice: 'Send was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_send
      @send = Send.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def send_params
      params.require(:send).permit(:address, :coment, :user)
    end
end

app/helpers/sends_helper.rb
module SendsHelper
end

app/views/sends/_form.html.erb
<div class="row justify-content-center">
  <div class="col-7" >
    <%= form_with(model: send, local: true) do |form| %>
      <% if send.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(send.errors.count, "error") %> prohibited this send from being saved:</h2>

          <ul>
          <% send.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <label>Dirección</label>
        <div class="row">
          <div class="col-md-6">
            <%= form.text_field :address,
            class: 'form-control' %>
          </div>
          <div class="col-md-2">
            <%= link_to '#', class:'btn btn-primary', id:"find-address" do %>
              <i class="fa fa-map-marker"></i>
            <% end %>
          </div>
        </div>
      </div>
      <br>
      <div class="field">
        <%= form.label :coment %><br>
        <%= form.text_area :coment %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>
<script>
$("#find-address").click(function(event) {
  $(this).html('<i class="fa fa-spinner fa-spin"</i>')
  event.preventDefault();
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(getAddress);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser"
  }
});

function getAddress(position) {
  var latitude = position.coords.latitude;
  var longitude = position.coords.longitude;

  $.ajax({
    url: '/geocoder/findaddress',
    type: 'GET',
    dataType: 'script',
    data: {latitude: latitude, longitude: longitude}
  })
  .done(function() {
    console.log("success");
  })
  .fail(function() {
    console.log("error");
  })
  .always(function() {
    $("#find-address").html('<i class="fa fa-map-marker"</i>')
  });
}

</script>

app/views/sends/edit.html.erb
<h1>Editing Send</h1>

<%= render 'form', send: @send %>

<%= link_to 'Show', @send %> |
<%= link_to 'Back', sends_path %>

app/views/sends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sends</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Coment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sends.each do |send| %>
      <tr>
        <td><%= send.address %></td>
        <td><%= send.coment %></td>
        <td><%= link_to 'Show', send %></td>
        <td><%= link_to 'Edit', edit_send_path(send) %></td>
        <td><%= link_to 'Destroy', send, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Send', new_send_path %>

app/views/sends/new.html.erb
<h1>New Send</h1>

<%= render 'form', send: @send %>

<%= link_to 'Back', sends_path %>

app/views/sends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @send.address %>
</p>

<p>
  <strong>Coment:</strong>
  <%= @send.coment %>
</p>

<%= link_to 'Edit', edit_send_path(@send) %> |
<%= link_to 'Back', sends_path %>